# Generated by Django 3.0.6 on 2021-04-24 12:27

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(blank=True, max_length=300, verbose_name='Degree')),
            ],
        ),
        migrations.CreateModel(
            name='FieldStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldStudy', models.CharField(blank=True, max_length=300, verbose_name='Field Study')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schools', models.CharField(blank=True, max_length=300, verbose_name='School Category')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', django_jalali.db.models.jDateField(verbose_name='Start Date')),
                ('endDate', django_jalali.db.models.jDateField(verbose_name='End Date')),
                ('grade', models.CharField(blank=True, max_length=200, verbose_name='Grade')),
                ('activitiesSocieties', models.CharField(blank=True, max_length=200, verbose_name='Activities and Societies')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degre', to='userprofile.Degree')),
                ('fieldStudy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Study', to='userprofile.FieldStudy')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schoo', to='userprofile.School')),
            ],
        ),
    ]
